version: '3.8'

services:
  bash-lab:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bash-lab
    stdin_open: true
    tty: true
    volumes:
      - ./scripts:/root/scripts
